---
title: "ab-calendar_exploration"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ab-calendar_exploration}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(evavelo)
library(magrittr)
library(dplyr)
```

```{r import data}
# Full data
#xlsx_path <- system.file("example-data/01_all.xlsx", package = "evavelo")
# Reduced size data
#xlsx_path <- system.file("example-data/02_simplified.xlsx", package = "evavelo")
xlsx_path <- here::here("inst", "example-data", "02_simplified.xlsx")
```

## Lire calendrier

```{r}
calendar <- read_calendrier(xlsx_path)
enquete <- read_enquete(xlsx_path)
comptage <- read_comptage(xlsx_path)


## Test when no error

evavelo:::check_diff(calendar, enquete) 

evavelo:::check_diff(calendar, comptage)
evavelo::check_evavelo(calendar, comptage, enquete)$log %>% message() 
## Test when some data is missing in enquete or comptage
comptage_trunc <- comptage %>% 
  filter(date_enq == first(date_enq))
enquete_trunc <- enquete %>% 
  filter(id_site_enq == first(id_site_enq))

evavelo:::check_diff(calendar, enquete_trunc) %>% 
  message()

evavelo:::check_diff(calendar, comptage_trunc) %>% 
  message()


evavelo::check_evavelo(calendar, comptage_trunc, enquete_trunc)$log %>% message()
## Test when missing date in calendrier
calendar_trunc <- tail(calendar, n = 3)

evavelo:::check_diff(calendar_trunc, enquete) %>% 
  message()

evavelo:::check_diff(calendar_trunc, comptage) %>% 
  message()

evavelo::check_evavelo(calendar_trunc, comptage, enquete)$log %>% message()

```

