---
title: "Utilisation de Eva-Scan"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Utilisation de Eva-Scan}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, include = FALSE}
library(evavelo)
library(magrittr)
library(dplyr)
```

## Import and clean file
Import des données

```{r import files}
# Full data
#xlsx_path <- system.file("example-data/01_all.xlsx", package = "evavelo")
# Corrected data
#xlsx_path <- here::here("inst", "example-data", "01a_all_correct.xlsx")
# Reduced size data
xlsx_path <- system.file("example-data/02_simplified.xlsx", package = "evavelo")
#xlsx_path <- here::here("inst", "example-data", "02_simplified.xlsx")


eva_data <- evavelo::read_evavelo(xlsx_path)

```

### Test input values

Si l'object eva_data n'a pas été géocodé au préalable, `process_evavelo()` va géocoder les villes avant de faire le traitement.
Un log du géocodage apparaitra dans les messages.

La fonction retourne une liste de valeurs créées ou modifiées.

```{r test}
result <- evavelo::process_evavelo(eva_data)

purrr::map(result, ~ head(.x,10))
```



